### ISSUE TITLE
zls won't compile

### ISSUE THREAD

**Issue by correabuscar** [BratishkaErik/bratishkaerik-overlay#1]
I'm hitting this issue https://github.com/zigtools/zls/issues/611

Note that I've also had to add:
```ebuild
KEYWORDS="~amd64"
```
or else:
```
...
*** Forking to drop superuser privileges ...
*** Updating the repositories using 12 parallel jobs...
*** No updates found (in 0 live packages)
->  emerge --oneshot --getbinpkg=n --usepkg-exclude  zls --usepkg=n

These are the packages that would be merged, in reverse order:

Calculating dependencies  ... done!

!!! All ebuilds that could satisfy "zls" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-util/zls-9999::localrepo (masked by: missing keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.


```

**Comment by correabuscar** [comment]
Can confirm this works now with `FEATURES=-userpriv`, otherwise(with `userpriv`) I get:
```
>>> Install dev-util/zls-9999 into /var/tmp/portage/dev-util/zls-9999/image
git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
fatal: detected dubious ownership in repository at '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/tmp/portage/dev-util/zls-9999/work/zls-9999
error: The following command exited with error code 128:
git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
error: the following build command failed with exit code 128:
/var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache/o/2bf54450f845f0a2ffa1d0a24d35e674/build /usr/bin/zig-stage1 /var/tmp/portage/dev-util/zls-9999/work/zls-9999 /var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache /var/tmp/portage/dev-util/zls-9999/homedir/.cache/zig install --prefix /usr --verbose
 * ERROR: dev-util/zls-9999::localrepo failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 122:  Called src_install
 *   environment, line 1107:  Called die
 * The specific snippet of code:
 *       DESTDIR="${D}" zig-stage1 build install --prefix "${EPREFIX}"/usr --verbose || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-util/zls-9999::localrepo'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/zls-9999::localrepo'`.
 * The complete build log is located at '/tmp/ebuild.logs/build/dev-util/zls-9999:20220902-174511.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-util/zls-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/zls-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
 * S: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'

```

from what I can tell, it's because `/var/tmp/portage/dev-util/zls-9999/work/zls-9999` is owned by `portage:portage`(due to `FEATURES=userpriv`) but `src_install()` is running as `root:root`.

There's probably nothing you can do, so I'm happy as it is, thank you!

**Comment by BratishkaErik** [comment]
@correabuscar I mistyped in my PR, and zig-stage1 is actually stage2, please see this comment https://github.com/gentoo/gentoo/pull/27112#discussion_r961898428

**Comment by BratishkaErik** [comment]
I think this is the reason why you have identical error message here https://github.com/ziglang/zig/issues/12725

**Comment by correabuscar** [comment]
The comment that you link to, github won't show me it. In fact, I cannot see any review. I'm just being shown the top of that PR page, but no current reviews are visible, even though if I hover over the comment link in your previous comment here, it shows me ` BratishkaErik reviewed
Suggested change I don't have Internet access on PC right now, so I ca…` but there's no trace of this in the actual PR, ergo I cannot see that comment, yet? :)

**Comment by BratishkaErik** [comment]
> Can confirm this works now with `FEATURES=-userpriv`, otherwise(with `userpriv`) I get:
> ```
> >>> Install dev-util/zls-9999 into /var/tmp/portage/dev-util/zls-9999/image
> git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
> fatal: detected dubious ownership in repository at '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory /var/tmp/portage/dev-util/zls-9999/work/zls-9999
> error: The following command exited with error code 128:
> git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
> error: the following build command failed with exit code 128:
> /var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache/o/2bf54450f845f0a2ffa1d0a24d35e674/build /usr/bin/zig-stage1 /var/tmp/portage/dev-util/zls-9999/work/zls-9999 /var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache /var/tmp/portage/dev-util/zls-9999/homedir/.cache/zig install --prefix /usr --verbose
>  * ERROR: dev-util/zls-9999::localrepo failed (install phase):
>  *   (no error message)
>  * 
>  * Call stack:
>  *     ebuild.sh, line 122:  Called src_install
>  *   environment, line 1107:  Called die
>  * The specific snippet of code:
>  *       DESTDIR="${D}" zig-stage1 build install --prefix "${EPREFIX}"/usr --verbose || die;
>  * 
>  * If you need support, post the output of `emerge --info '=dev-util/zls-9999::localrepo'`,
>  * the complete build log and the output of `emerge -pqv '=dev-util/zls-9999::localrepo'`.
>  * The complete build log is located at '/tmp/ebuild.logs/build/dev-util/zls-9999:20220902-174511.log'.
>  * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-util/zls-9999/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/dev-util/zls-9999/temp/environment'.
>  * Working directory: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
>  * S: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
> 
> ```
> 
> from what I can tell, it's because `/var/tmp/portage/dev-util/zls-9999/work/zls-9999` is owned by `portage:portage`(due to `FEATURES=userpriv`) but `src_install()` is running as `root:root`.
> 
> There's probably nothing you can do, so I'm happy as it is, thank you!
> 

https://packages.gentoo.org/packages/dev-vcs/git

> 2.35.2 was a quick release to mitigate a security issue (bug #838127), but introduces problems of its own with e.g. Portage. bug #838223. Pending investigation both on the Portage side and potentially upstream (as there's at least some UX issues with 2.35.2+ with the new "safe directory" mechanism). Earlier versions are still safe as long as you do not use git commands on a local repository controlled by a user you do not trust.

Try to disable "safe-directory" USE flag

**Comment by BratishkaErik** [comment]
> The comment that you link to, github won't show me it. In fact, I cannot see any review. I'm just being shown the top of that PR page, but no current reviews are visible, even though if I hover over the comment link in your previous comment here, it shows me ` BratishkaErik reviewed
> Suggested change I don't have Internet access on PC right now, so I ca…` but there's no trace of this in the actual PR, ergo I cannot see that comment, yet? :)
> 

Change `newbin zig2 zig-stage1` to newbin zig1 zig-stage1

**Comment by correabuscar** [comment]
> > The comment that you link to, github won't show me it. In fact, I cannot see any review. I'm just being shown the top of that PR page, but no current reviews are visible, even though if I hover over the comment link in your previous comment here, it shows me ` BratishkaErik reviewed Suggested change I don't have Internet access on PC right now, so I ca…` but there's no trace of this in the actual PR, ergo I cannot see that comment, yet? :)
> 
> Change `newbin zig2 zig-stage1` to `newbin zig1 zig-stage1` in ebuild

```
>>> Compiling source in /var/tmp/portage/dev-util/zls-9999/work/zls-9999 ...
Invalid argument: -Drelease-safe
See `zig-stage1 --help` for detailed usage information
 * ERROR: dev-util/zls-9999::localrepo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 122:  Called src_compile
 *   environment, line 1098:  Called die
 * The specific snippet of code:
 *       zig-stage1 build -Drelease-safe -Ddata_version=master --verbose || die
 * 
 * If you need support, post the output of `emerge --info '=dev-util/zls-9999::localrepo'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/zls-9999::localrepo'`.
 * The complete build log is located at '/tmp/ebuild.logs/build/dev-util/zls-9999:20220902-182201.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-util/zls-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/zls-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
 * S: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'

```

Now `zig-stage1` seems very different from `zig`:
```
# zig-stage1 --help
Usage: zig-stage1 [options]            builds an object file

Options:
  --color [auto|off|on]        enable or disable colored error messages
  --name [name]                override output name
  -femit-bin=[path]            Output machine code
  -fcompiler-rt                Always include compiler-rt symbols in output
  --pkg-begin [name] [path]    make pkg available to import and push current pkg
  --pkg-end                    pop current pkg
  -ODebug                      build with optimizations off and safety on
  -OReleaseFast                build with optimizations on and safety off
  -OReleaseSafe                build with optimizations on and safety on
  -OReleaseSmall               build with size optimizations on and safety off
  -fsingle-threaded            source may assume it is only used single-threaded
  -dynamic                     create a shared library (.so; .dll; .dylib)
  --strip                      exclude debug symbols
  -target [name]               <arch>-<os>-<abi> see the targets command
  -mcpu [cpu]                  specify target CPU and feature set
  --verbose-ir                 enable compiler debug output for Zig IR
  --verbose-llvm-ir            enable compiler debug output for LLVM IR
  --verbose-cimport            enable compiler debug output for C imports
  --verbose-llvm-cpu-features  enable compiler debug output for LLVM CPU features

```
```
# zig --help
Usage: zig [command] [options]

Commands:

  build            Build project from build.zig
  init-exe         Initialize a `zig build` application in the cwd
  init-lib         Initialize a `zig build` library in the cwd

  ast-check        Look for simple compile errors in any set of files
  build-exe        Create executable from source or object files
  build-lib        Create library from source or object files
  build-obj        Create object from source or object files
  fmt              Reformat Zig source into canonical form
  run              Create executable and run immediately
  test             Create and run a test build
  translate-c      Convert C code to Zig code

  ar               Use Zig as a drop-in archiver
  cc               Use Zig as a drop-in C compiler
  c++              Use Zig as a drop-in C++ compiler
  dlltool          Use Zig as a drop-in dlltool.exe
  lib              Use Zig as a drop-in lib.exe
  ranlib           Use Zig as a drop-in ranlib

  env              Print lib path, std path, cache directory, and version
  help             Print this help and exit
  libc             Display native libc paths file or validate one
  targets          List available compilation targets
  version          Print version number and exit
  zen              Print Zen of Zig and exit

General Options:

  -h, --help       Print command-specific usage

Debug Commands:

  changelist       Compute mappings from old ZIR to new ZIR
```

**Comment by correabuscar** [comment]
Oh, can compile `zls` now with `zig-stage2` (and `FEATURES=userpriv`, and with `dev-vcs/git` with `USE=-safe-directory` , thanks!)

But doesn't work with `zig`(is it stage3?) instead of `zig-stage2`, assuming zig ebuild has:
```
    dodoc ../README.md                                                                                                                                            
    newbin zig1 zig-stage1                                                                                                                                        
    newbin zig2 zig-stage2                                                                                                                                        
    newbin stage3/bin/zig zig-stage3       
```

**Comment by correabuscar** [comment]
> The comment that you link to, github won't show me it. In fact, I cannot see any review. I'm just being shown the top of that PR page, but no current reviews are visible, even though if I hover over the comment link in your previous comment here, it shows me ` BratishkaErik reviewed Suggested change I don't have Internet access on PC right now, so I ca…` but there's no trace of this in the actual PR, ergo I cannot see that comment, yet? :)

re this, I'm thinking comments aren't visible until Submit Review button is pushed, until then you can keep adding comments but they are visible only to you (and maybe to the team?)

**Comment by BratishkaErik** [comment]
Sorry, it looks like we will not have have stage1 for some time (zig2 is compiled without stage1 support, and zig1 is stage0, not stage1, so I need to fix zig3 target)

**Comment by BratishkaErik** [comment]
> Can confirm this works now with `FEATURES=-userpriv`, otherwise(with `userpriv`) I get:
> 
> ```
> >>> Install dev-util/zls-9999 into /var/tmp/portage/dev-util/zls-9999/image
> git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
> fatal: detected dubious ownership in repository at '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory /var/tmp/portage/dev-util/zls-9999/work/zls-9999
> error: The following command exited with error code 128:
> git -C /var/tmp/portage/dev-util/zls-9999/work/zls-9999 describe --match *.*.* --tags 
> error: the following build command failed with exit code 128:
> /var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache/o/2bf54450f845f0a2ffa1d0a24d35e674/build /usr/bin/zig-stage1 /var/tmp/portage/dev-util/zls-9999/work/zls-9999 /var/tmp/portage/dev-util/zls-9999/work/zls-9999/zig-cache /var/tmp/portage/dev-util/zls-9999/homedir/.cache/zig install --prefix /usr --verbose
>  * ERROR: dev-util/zls-9999::localrepo failed (install phase):
>  *   (no error message)
>  * 
>  * Call stack:
>  *     ebuild.sh, line 122:  Called src_install
>  *   environment, line 1107:  Called die
>  * The specific snippet of code:
>  *       DESTDIR="${D}" zig-stage1 build install --prefix "${EPREFIX}"/usr --verbose || die;
>  * 
>  * If you need support, post the output of `emerge --info '=dev-util/zls-9999::localrepo'`,
>  * the complete build log and the output of `emerge -pqv '=dev-util/zls-9999::localrepo'`.
>  * The complete build log is located at '/tmp/ebuild.logs/build/dev-util/zls-9999:20220902-174511.log'.
>  * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-util/zls-9999/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/dev-util/zls-9999/temp/environment'.
>  * Working directory: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
>  * S: '/var/tmp/portage/dev-util/zls-9999/work/zls-9999'
> ```
> 
> from what I can tell, it's because `/var/tmp/portage/dev-util/zls-9999/work/zls-9999` is owned by `portage:portage`(due to `FEATURES=userpriv`) but `src_install()` is running as `root:root`.
> 
> There's probably nothing you can do, so I'm happy as it is, thank you!

Try to enable both `userfetch` and `userpriv` (and revert disabling "safe-directory" USE flag). That's how it worked on my system.
